name = "json_to_quaff"
version = "0.0.1"
license = "MIT"
author = "Giovanni Facco"
maintainer = "gfacco@gmail.com"
copyright = "2022 Giovanni Facco"

[dependencies]
quaff = { git = "https://gitlab.com/everythingfunctional/quaff.git", tag = "v1.0.1" }
rojff = { git = "https://gitlab.com/everythingfunctional/rojff.git", tag = "v2.0.3" }
erloff = { git = "https://gitlab.com/everythingfunctional/erloff.git", tag = "v2.3.1" }


[dev-dependencies]
veggies = { git = "https://gitlab.com/everythingfunctional/veggies.git", tag = "v1.1.3" }
quaff_asserts = { path = "build/dependencies/quaff/quaff_asserts" }

[[test]]
name = "unit_test"
source-dir = "test"
main = "main.f90"